services:
  chain_command.manager:
    class: Timofiy\ChainCommandBundle\Manager\ChainCommandManager

  chain_command.subscriber:
    class: Timofiy\ChainCommandBundle\EventSubscriber\ChainCommandEventSubscriber
    arguments: [ '@chain_command.manager', '@logger' ]
    tags:
      - { name: kernel.event_subscriber, event: console.command }